github:
  owner_url: https://github.com/thejefe
  owner_name: TheJefe

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-font-awesome-sass
  - jekyll-bootstrap-sass

bootstrap:
  assets: true

font-awesome:
  assets: true
